theme: jekyll-theme-minimal
logo: ../images/app_ico_small.jpg
description: Developer Resources
owner_name: Upsilon Dynamics Inc.
owner_url: https://www.upsilondynamics.com    
future: true

collections:
  pages:
    output: false
    permalink: /pages/:name

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
